apiVersion: v1
kind: Service
metadata:
  name: realtor-agentic-ai-service
spec:
  selector:
    app: realtor-agentic-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

